### ISSUE TITLE
What GPU did you use?

### ISSUE THREAD

**Issue by victormashkov19** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#8]
I have tested code with NVIDIA TITAN RTX (24GB GPU RAM), but OOM occured.
What GPU did you use to train network?

**Comment by s60912frank** [comment]
Same problem, though I'm using a single GTX1070(8GB VRAM).
Had to make face alignment run on CPU, it's really slow but it worked.

**Comment by victormashkov19** [comment]
When I tested in CPU mode, peak memory usage exceeds 30GB.

**Comment by s60912frank** [comment]
Oops, sorry, I misread your question. I was taking about webcam demo.

**Comment by vincent-thevenin** [comment]
@victormashkov19 I used the Nvidia Tesla K80, I don't exceed 12GB of gpu memory with batch size of 2 but that's with the test dataset.

Did you use the full dataset?
During what part of training did the OOM error occur?

**Comment by victormashkov19** [comment]
I use full VoxCeleb2 dataset in the environment Windows 10 x64, Python 3.6(Anaconda3-5.2.0), Cuda 10.0.
A strange thing is that when using small dataset (321 person, 55251 videos, 12.5GB), the saved model is 1443MB size, when using full dataset, saved model is greater 2554MB.
OOM error message is as follows.
Saving latest...
...Done saving latest
Pytorch_VGGFACE_IR.py:117: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  prob            = F.softmax(fc8_1)
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    lossD.backward(retain_graph=False)
  File "C:\Anaconda3\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 2.08 GiB (GPU 0; 24.00 GiB total capacity; 16.06 GiB already allocated; 1.49 GiB free; 1.82 GiB cached)

At what environment did you tested?

**Comment by rmd2** [comment]
Hi! I am facing the same problem... I am trying to continue the training process using a GTX1080 on Ubuntu 18.04, but I always get an Out Of Memory error when running ¨python train.py¨. Do you use any special step? Or I really need a gpu with more memory?

Thanks!

**Comment by vincent-thevenin** [comment]
Hi @victormashkov19  @rmd2,
I made a recent commit in order to use less gpu memory during the gradient compute of both VGG networks. Can you pull these changes and tell me if there's any improvement?

Also I don't know if you did it but I changed the network I use in the README prerequisites. The new one improves memory usage as well please redo the prerequisites if you have not.

Using the full dataset compared to the test dataset will use more gpu memory as the Discriminator size depends on the dataset size.

If you need more gpu memory, you can always reduce the batch size during training. To do that modify line 63 in train.py: `dataLoader = DataLoader(dataset, batch_size=2, shuffle=True)`, current setting is batch size of 2, change it to 1.

Please tell me if you still have memory errors.

**Comment by danny-wu** [comment]
Has anyone been able to get this to run on a GPU with 6GB VRAM?

**Comment by jw0766hub** [comment]
nvidia 2060 and 6GB VRAM.
I changed  line 39 to `lossface += self.l1_loss(x_feat, xhat_feat).item()` which was `lossface += self.l1_loss(x_feat, xhat_feat)`
also chaned line 107 and 123 too. ans change batch size to 1 and it works
